// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtnfjrurvvstpjglmjcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bmZqcnVydnZzdHBqZ2xtamNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDE4MDYsImV4cCI6MjA2MTM3NzgwNn0.CG4cMYos57Fx4E8qrU1NSPepmW9ZVgFhrmLNBpLlLaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);